### ISSUE TITLE
Need Installation Documentation (anything would help)

### ISSUE THREAD

**Issue by david-lareau-nrc** [GlobalDataverseCommunityConsortium/dataverse-language-packs#22]
the README.md says "API Documentation for deploying language files is still under development". Any example would be greatly appreciated.

After reading the documentation at http://guides.dataverse.org/en/latest/installation/config.html
I tried the following but I get a server internal error. 

My version of dataverse is v. 4.14 build 1326-57a392d

Step 1)

```
curl http://localhost:8080/api/admin/settings/:Languages -X PUT -d '[{  "locale":"en", "title":"English"},  {  "locale":"fr", "title":"Français"}]'
```
I can now see the toggle button in the navbar (though it is not functional yet).

Step 2)

```
cd /var/www/dataverse
git clone https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs.git
git checkout --track origin/dataverse-v4.14
./asadmin create-jvm-options '-Ddataverse.lang.directory=/var/www/dataverse/dataverse-language-packs'

```
When loading any page I get
java.util.MissingResourceException: Can't find bundle for base name Bundle, locale en

I verified that all permissions are indeed rwxr-xr-x. Anything obvious that I'm doing wrong? Do I have to move the language pack in docroot of glasshfish?

**Comment by david-lareau-nrc** [comment]
Just saw that the opened issue "How to Help Translate Dataverse Into Your Language" is more about how to install than translate, so my question is a dupe. Closing.

**Comment by JayanthyChengan** [comment]
@david-lareau-nrc - Please find the config documentation in develop branch:
https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/installation/config.rst#internationalization

**Comment by 4tikhonov** [comment]
@david-lareau-nrc, thanks for trying this functionality! We're going to try Weblate localization tool to keep all language packages up-to-date.

**Comment by bikramj** [comment]
We at Scholars Portal are testing translations management with Weblate and [Mojito](http://www.mojito.global/), just testing which one is easier to use and integrate with the workflow. we have local installations of both.

**Comment by 4tikhonov** [comment]
@bikramj, great to hear! Can you share your insights which one is easier?

**Comment by bikramj** [comment]
@4tikhonov, Mojito is really simple to install and use whereas Weblate offers a lot more functionality. I am still testing Weblate and will post my findings here in few days.

**Comment by pdurbin** [comment]
> Just saw that the opened issue "How to Help Translate Dataverse Into Your Language" is more about how to install than translate, so my question is a dupe. Closing.

@david-lareau-nrc actually my intended audience for #10 was translators so I do think we should consider either reopening this issue for a sysadmin audience. (I don't have the power to reopen issues here.)

@bikramj do you still want to use https://jenkins.dataverse.org for anything? All the config is at https://github.com/IQSS/dataverse-jenkins and I'm happy to work with you and others to add as many jobs as we need. I just made a similar offer to @4tikhonov over at https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/issues/26#issuecomment-502069499 (about Weblate, by the way).

> I am still testing Weblate and will post my findings here in few days.

A dedicated issue about Weblate might be nice. I imagine that both audiences I'm talking about (translators and sysadmins) would be interested in the percentage translation of their languages of interest.
