### ISSUE TITLE
Link broken to Spanish translation on README.md

### ISSUE THREAD

**Issue by ysuarez** [GlobalDataverseCommunityConsortium/dataverse-language-packs#30]
FYI, the link for the Spanish translation returns a 404 error.

The link text is:
"Spanish, 4.9.4" 

The link is currently pointing to:
https://github.com/IQSS/dataverse-docker/blob/master/dataversedock/dataverse-property-files/es-ES/

**Comment by ysuarez** [comment]
If someone posts the correct link I can submit a pull request to fix the issue.

**Comment by mhvezina** [comment]
Maybe @juancorr can help?

**Comment by juancorr** [comment]
I am sorry Marie-Hélène,
  Should I make a pull request to add Spanish translations to the
dataverse-language-packs github?

  We have translate several Dataverse versions.

Juan Corrales

**Comment by mhvezina** [comment]
Hola @juancorr ,

My understanding is that yes indeed, you can make a pull request to add the Spanish translation to the dataverse-language-packs, that would be very much appreciated I'm sure. Latest branch is the develop branch, but you can also make pull request to specific branches (from v4.10.1 to v4.14)... well at least this is what I did for the fr_CA translations over time.

**Comment by juancorr** [comment]
Merci beaucoup @mhvezina,

  I have created the pull request to the v4.11 version. I was wrong, we
have not another translations for the new language packs model.

  I hope we will synchronized with the develop branch in September.

Juan Corrales

**Comment by mhvezina** [comment]
@ysuarez link to the Spanish version has been updated on the https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/blob/develop/README.md page.

Thank you @juancorr for your contribution.
