### ISSUE TITLE
French Translation required for version 4.15.1

### ISSUE THREAD

**Issue by JayanthyChengan** [GlobalDataverseCommunityConsortium/dataverse-language-packs#34]
@mhvezina 
created new branch dataverse-v4.15.1(https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/tree/dataverse-v4.15.1)

please add french translations for new/modified properties in below files

en_US/Bundle.properties 

Click "Files changed" tab at https://github.com/IQSS/dataverse/compare/v4.15...v4.15.1 to view differences between tag v4.15 and v4.15.1

**Comment by mhvezina** [comment]
Done, #36
