### ISSUE TITLE
Fr_CA : missing translation for subject facet

### ISSUE THREAD

**Issue by tcoupin** [GlobalDataverseCommunityConsortium/dataverse-language-packs#45]
https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/blob/86348762007fa6a2979e3d40fc54cd05afb34430/fr_CA/Bundle_fr.properties#L2385

Missing translation for subject facet : 
`staticSearchFields.subject_ss=Sujet`

**Comment by mhvezina** [comment]
Bonjour Thibault,

As I already said, fr_CA is rigorously aligned with the en_US translation. Those facets headings ("Sujet", "Auteur", etc.) are missing for now (see https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/pull/43#issuecomment-533135656). I will take care of the fr_CA translation once the new en_US version becomes available.

Bonne journée,

Marie-Hélène
