### ISSUE TITLE
PR en_US and fr_FR for dataverse-v4.17

### ISSUE THREAD

**Issue by tcoupin** [GlobalDataverseCommunityConsortium/dataverse-language-packs#46]
I can't open a PR since branch dataverse-v4.17 does not exist.
-> https://github.com/tcoupin/dataverse-language-packs/tree/dataverse-v4.17

**Comment by JayanthyChengan** [comment]
Created the new branch https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/tree/dataverse-v4.17

**Comment by tcoupin** [comment]
:muscle:
