### ISSUE TITLE
fr_CA French Translation required for version 4.18.1

### ISSUE THREAD

**Issue by JayanthyChengan** [GlobalDataverseCommunityConsortium/dataverse-language-packs#52]
@mhvezina 
created new branch dataverse-v4.18.1(https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/tree/dataverse-v4.18.1)

please add french translations for new/modified properties in below files

en_US/Bundle.properties

Click "Files changed" tab at https://github.com/IQSS/dataverse/compare/v4.18...v4.18.1
to view differences between tag v4.18 and v4.18.1

Thanks

**Comment by mhvezina** [comment]
@JayanthyChengan 

Done (https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/pull/55)
