### ISSUE TITLE
New french translation required - develop branch

### ISSUE THREAD

**Issue by JayanthyChengan** [GlobalDataverseCommunityConsortium/dataverse-language-packs#8]
@mhvezina -

Few additional terms in bundle.properties (develop branch ) where translation required
https://github.com/IQSS/dataverse/compare/v4.12...develop#diff-dc3b2032fe992f07917245298ced7ec7

![image](https://user-images.githubusercontent.com/12862735/55974195-2ab52180-5c55-11e9-9770-b411ad406d1b.png)

**Comment by mhvezina** [comment]
@JayanthyChengan 

I just completed the translation update for version 4.14. (https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/pull/17 )
Maybe we can skip (close) this request for now without further work and wait for next version? and/or do you want to update develop branch and I could provide translation for ongoing work if any?

**Comment by JayanthyChengan** [comment]
@mhvezina 
I am ok with closing this issue and work later for new release.  Thanks for all your work.
