### ISSUE TITLE
fr_CA French Translation required for version 5.1.1

### ISSUE THREAD

**Issue by JayanthyChengan** [GlobalDataverseCommunityConsortium/dataverse-language-packs#82]
@mhvezina
created new branch dataverse-v5.1.1(https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/tree/dataverse-v5.1.1)

please add french translations for new/modified properties in below files

en_US/ValidationMessages.properties
en_US/biomedical.properties

Thanks

**Comment by mhvezina** [comment]
Bonjour @JayanthyChengan 

Done. https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/pull/83
