### ISSUE TITLE
Files for v5.10 in en_US and fr_FR

### ISSUE THREAD

**Issue by bappun** [GlobalDataverseCommunityConsortium/dataverse-language-packs#91]
We created a new orphan branch for v5.10 en_US and fr_FR properties in our fork here: https://github.com/CDSP-SCPO/dataverse-language-packs/tree/dataverse-v5.10.

We copied the v5.10 en_US files from here: https://github.com/IQSS/dataverse/tree/v5.10/src/main/java.

Would it be possible to add the files from this branch to the repo, or create a new one from which we will make a PR?

**Comment by 4tikhonov** [comment]
Nice, @bappun! Let's PR to https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/tree/dataverse-v5.10 then!
